name: Deploy to ECS

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Update ECS service
        uses: aws-actions/amazon-ecs-update-service@v2
        with:
          cluster: nfl-bets-backend-cluster
          service: nfl-bets-backend-service
          task-definition: nfl-bets-backend-task
          force-new-deployment: true
