name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: KGauthier17/nfl-bets-backend:${{ github.sha }}

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop nfl-bets-backend || true
            docker rm nfl-bets-backend || true
            docker pull KGauthier17/nfl-bets-backend:${{ github.sha }}
            docker run -d --name nfl-bets-backend -p 80:80 KGauthier17/nfl-bets-backend:${{ github.sha }}