name: Scheduled Run Jobs

on:
  schedule:
    - cron: '* */4 * * *'

jobs:
  call-run-jobs-endpoint:
    runs-on: ubuntu-latest
    env:
      SYNC_ENDPOINT: ${{ secrets.SYNC_ENDPOINT }}
    steps:
      - name: Call /run-jobs endpoint
        run: |
          curl -X GET $SYNC_ENDPOINT